---
check:
  global:
    statements: 100
    lines: 100
    branches: 100
    functions: 100
reporting:
  watermarks:
    statements: [90, 100]
    lines: [90, 100]
    functions: [90, 100]
    branches: [90, 100]
