var routes = module.exports = require('http-hash')()

routes.set('/', require('./metadata'))
routes.set('/forms', require('./forms'))
routes.set('/forms/:digest', require('./form'))
routes.set('/forms/:digest/projects', require('./form-projects'))
routes.set('/forms/:digest/parents', require('./form-parents'))
routes.set('/forms/:digest/headings', require('./form-headings'))
routes.set('/publishers', require('./publishers'))
routes.set('/publishers/:publisher/projects', require('./publisher-projects'))
routes.set('/publishers/:publisher/projects/:project/editions', require('./project-editions'))
routes.set('/publishers/:publisher/projects/:project/editions/:edition', require('./edition'))
routes.set('/publishers/:publisher/projects/:project/editions/:edition/form', require('./edition-form'))
routes.set('/terms/:term/definitions', require('./term-definitions'))
routes.set('/terms/:term/uses', require('./term-uses'))
routes.set('/headings/:heading/forms', require('./heading-forms'))
routes.set('/headings/:heading/references', require('./heading-references'))

var listNamespace = require('./list-namespace')
;[ 'heading', 'term', 'digest' ].forEach(function(namespace) {
  var pattern = ( '/' + namespace + 's')
  routes.set(pattern, listNamespace(namespace)) })
