var routes = module.exports = require('http-hash')()

routes.set('/', require('./metadata'))
routes.set('/forms', require('./forms'))
routes.set('/forms/:digest', require('./form'))
routes.set('/forms/:digest/projects', require('./form-projects'))
routes.set('/publishers', require('./publishers'))
routes.set('/publishers/:publisher/projects', require('./publisher-projects'))
routes.set('/publishers/:publisher/projects/:project/editions', require('./project-editions'))
routes.set('/publishers/:publisher/projects/:project/editions/:edition', require('./edition'))
routes.set('/publishers/:publisher/projects/:project/editions/:edition/form', require('./edition-form'))
